2018-01-22 20:06:43,670 [7] INFO  BaseLog [(null)] - [IsAuthorized]IsCheckIP=False,IsCheckLogin=False,CheckModuleRight=,用户请求的地址=http://www1.chitunion.com/api/DictInfo/GetDictInfoByTypeID?typeID=47,UrlRefer=http://www1.chitunion.com/static/advertister/sort_list.html
2018-01-22 20:06:43,679 [8] INFO  BaseLog [(null)] - [IsAuthorized]IsCheckIP=False,IsCheckLogin=True,CheckModuleRight=,用户请求的地址=http://www1.chitunion.com/api/MediaMatching/GetCartCount,UrlRefer=http://www1.chitunion.com/static/advertister/sort_list.html
2018-01-22 20:06:43,717 [8] INFO  BaseLog [(null)] - [AuthorizedResult]用户验证失败,CheckLogin=False
2018-01-22 20:06:43,679 [11] INFO  BaseLog [(null)] - [IsAuthorized]IsCheckIP=False,IsCheckLogin=False,CheckModuleRight=,用户请求的地址=http://www1.chitunion.com/api/DictInfo/GetDictInfoByTypeID?typeID=6,UrlRefer=http://www1.chitunion.com/static/advertister/sort_list.html
2018-01-22 20:06:44,172 [11] INFO  BaseLog [(null)] - [IsAuthorized]IsCheckIP=False,IsCheckLogin=False,CheckModuleRight=,用户请求的地址=http://www1.chitunion.com/api/MediaMatching/GetMediaMatchingList?ListType=wx_list&keyword=&PageIndex=1&PageSize=20&CategoryID=-1&MaxFansCount=-1&MinFansCount=-1&MaxPrice=-1&MinPrice=-1&ProvinceID=-1&CityID=-1&ADPositionID=-1&ReferenceType=-1&SortField=-1&SortIndex=-1,UrlRefer=http://www1.chitunion.com/static/advertister/sort_list.html
2018-01-22 20:06:44,402 [11] ERROR BaseLog [(null)] - Chitunion_WebApi――异常
System.OperationCanceledException: 已取消该操作。
   在 System.Threading.CancellationToken.ThrowOperationCanceledException()
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2018-01-22 20:06:44,533 [11] INFO  BaseLog [(null)] - 发邮件开始：
2018-01-22 20:06:44,607 [11] INFO  BaseLog [(null)] - 发送邮件给谁:masj@xingyuanauto.com
2018-01-22 20:06:44,607 [11] INFO  BaseLog [(null)] - 发送邮件给谁:lix@xingyuanauto.com
2018-01-22 20:06:44,607 [11] INFO  BaseLog [(null)] - 发送邮件给谁:hant@xingyuanauto.com
2018-01-22 20:06:44,607 [11] INFO  BaseLog [(null)] - 发送邮件给谁:lihf@xingyuanauto.com
2018-01-22 20:06:44,607 [11] INFO  BaseLog [(null)] - 发送邮件给谁:zhanglb@xingyuanauto.com
2018-01-22 20:06:44,608 [11] INFO  BaseLog [(null)] - 发送邮件给谁:zhangjl@xingyuanauto.com
2018-01-22 20:06:46,044 [11] INFO  BaseLog [(null)] - 发邮件结束！
